### PR TITLE
Prevent potential peer list mutation

### PR DESCRIPTION
**Pull request by rgolangh**
Use a copy of a peer list instead of a reference to prevent mutation
of that list outside of the inner lock. Without this the lock
taked inside any guarded block is just useless because the list
reference just leaks out.

Signed-off-by: Roy Golan <rgolan@redhat.com>

### CODE REVIEW

**Comment by rgolangh** [comment]
@n1r1 PTAL

**Comment by n1r1** [comment]
@slintes what's your take on this?

**Comment by n1r1** [comment]
in [this line](https://github.com/medik8s/poison-pill/blob/5aa30162c5139b80903e7d3e9d7cec0a6f02dd69/pkg/apicheck/check.go#L116) we have:
`nodesToAsk := c.config.Peers.GetPeers().Items`

and later we modify `nodesToAsk`, will it affect the peers in `peers.go`?
do we have a data race here when `peers.go` is writing to `peers` while it's being used by `check.go`?

**Comment by slintes** [comment]
I think this is a good improvement to make code safer 👍🏼 
However, it isn't an issue in `check.go` today, because it uses the `Items` slice, and it doesn't matter if you get this from a pointer or value "parent", it is always a copy.
Maybe GetPeers() should even return the items directly...?

**Pull request merged**
