### PR TITLE
Fix the container image name in Makefile

### PR DESCRIPTION
**Pull request by rgolangh**
Signed-off-by: Roy Golan <rgolan@redhat.com>

### CODE REVIEW

**Comment by rgolangh** [comment]
This PR depends on @n1r1 pushing an annotated tag (hence the action failure on trying to docker build -t with an empty tag)

**Comment by n1r1** [comment]
@rgolangh 
pushed annotated tag

**Comment by rgolangh** [comment]
https://github.com/medik8s/poison-pill/pull/60/checks#step:4:3476

This looks good now.

**Pull request merged**
