### PR TITLE
Reduce flakiness of 2e test

### PR DESCRIPTION
**Pull request by slintes**
- make `killApiConnection` async, the execution time of the synced version isn't reliable
- let `checkNoNodeRecreate` consistently do the check for some minutes instead

### CODE REVIEW

**Comment by slintes** [comment]
/hold

run e2e a few times to see if this helps

**Comment by slintes** [comment]
/retest

no clue if this makes things better... but I think it also doesn't make things worse

**Comment by n1r1** [comment]
yeah, I think https://github.com/medik8s/poison-pill/pull/72 makes a real improvement.
the last failure is the first to fail on logs

**Comment by n1r1** [comment]
I believe that https://github.com/medik8s/poison-pill/pull/107 has done similar thing but with different approach - blocking until context is expected to expire. e2e test seems to be much more stable now (5 out of 5).
I'm closing this, let me know if you have any objection

**Pull request closed without merging**
