### PR TITLE
Remove service account yaml

### PR DESCRIPTION
**Pull request by ShellyKatz**
removed config/rbac/service_account.yaml and bundle/manifests/poison-pill-controller-manager_v1_serviceaccount.yaml files.

### CODE REVIEW

**Review by slintes — CHANGES_REQUESTED** [review]
I think removing `config/rbac/service_account.yaml` isn't a good idea, because that will break deployment via `make deploy`. I knew we don't have that manifest in the bundle of NMO, and wanted to find out why... turns out that it's just the version of `operator-sdk`, version 1.12.0 does not put the service account manifest into the bundle 🤷🏼‍♂️ 
Suggestion: use a fixed version of `operator-sdk`, which is installed by the `Makefile`. See https://github.com/kubevirt/node-maintenance-operator/blob/master/Makefile#L230 and all lines containing `OPERATOR_SDK`. Then delete the bundle dir, run `make bundle`, and see if the result is good 🙂

**Comment by n1r1** [comment]
> I think removing `config/rbac/service_account.yaml` isn't a good idea, because that will break deployment via `make deploy`. I knew we don't have that manifest in the bundle of NMO, and wanted to find out why... turns out that it's just the version of `operator-sdk`, version 1.12.0 does not put the service account manifest into the bundle 🤷🏼‍♂️ Suggestion: use a fixed version of `operator-sdk`, which is installed by the `Makefile`. See https://github.com/kubevirt/node-maintenance-operator/blob/master/Makefile#L230 and all lines containing `OPERATOR_SDK`. Then delete the bundle dir, run `make bundle`, and see if the result is good slightly_smiling_face


CVP will start failing operators with service account that is already defined in CSV, so this is a must, at least downstream.
and forward looking, this will be a must in OSDK and having that SA file is against their recommendation.
for more details see:
https://issues.redhat.com/browse/ECOPROJECT-352
https://github.com/operator-framework/operator-sdk/issues/5244

I didn't think about the `make deploy` case TBH.
I prefer to install the bundle. maybe it worth taking this to the operator-sdk team

**Comment by n1r1** [comment]
@ShellyKatz thanks for the PR!
I believe there are two non-related commits here that should be removed: 
c5db7e4 and  e89bc4c which describe metrics stuff

**Comment by slintes** [comment]
It has to be removed from `/bundle`, that's what OLM / CVP etc sees, because OLM will create the service account for you.
But it should not be removed from `/config`, that will break dev flow using `make deploy`, which does not use OLM, so we don't get a service account for free.

**Comment by n1r1** [comment]
> It has to be removed from `/bundle`, that's what OLM / CVP etc sees, because OLM will create the service account for you. But it should not be removed from `/config`, that will break dev flow using `make deploy`, which does not use OLM, so we don't get a service account for free.

correct. but we need to make sure that `make bundle` doesn't copy it again from the config folder
cc @ShellyKatz

**Comment by slintes** [comment]
yes, and that is just updating operator-sdk...

**Comment by slintes** [comment]
@ShellyKatz automatic backport to the release-0.3 branch doesn't work, can you create a new PR targeting that branch manually please?

**Pull request merged**
